# Generated by Django 4.1 on 2025-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('Cedula_Visitante', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_Visitante', models.CharField(max_length=100)),
                ('Edad_Visitante', models.IntegerField()),
            ],
        ),
    ]
