# Generated by Django 4.1 on 2025-07-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='Cedula_Visitante',
            new_name='Cédula_Visitante',
        ),
    ]
